cabal-version:      3.0
name:               wxr2pandoc
version:            0.1.0.0
-- synopsis:
-- description:
license:            MIT
license-file:       LICENSE
author:             ARATA Mizuki
maintainer:         minorinoki@gmail.com
-- copyright:
category:           Text
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  WXR2Pandoc.WXR
                      WXR2Pandoc.Filter
                      WXR2Pandoc.Write
                      WXR2Pandoc.ParseHTML
    -- other-modules:
    -- other-extensions:
    build-depends:    base >=4.19.0.0 && <4.23,
                      text ^>=2.1.3,
                      mtl ^>=2.3.1,
                      xml-conduit ^>=1.10.1.0,
                      pandoc >=3.7.0.2 && <3.9,
                      pandoc-types ^>=1.23.1,
                      time >=1.12.2 && <1.16,
                      aeson ^>=2.2.3.0,
                      containers >=0.7 && <0.9,
                      attoparsec ^>=0.14.4,
                      tagsoup ^>=0.14.8,
                      bytestring ^>=0.12.2.0,
                      network-uri >=2.6.4.2 && <2.8
    hs-source-dirs:   src
    default-language: GHC2021

executable wxr2pandoc
    import:           warnings
    main-is:          Main.hs
    -- other-modules:
    -- other-extensions:
    build-depends:
        base >=4.19.0.0 && <4.23,
        text ^>=2.1.3,
        optparse-applicative >=0.18.1.0 && <0.20,
        bytestring ^>=0.12.2.0,
        directory >=1.3.8.5 && <1.4,
        filepath >=1.4.200.1 && <1.6,
        pandoc >=3.7.0.2 && <3.9,
        pandoc-types ^>=1.23.1,
        http-client >=0.7.17 && <0.8,
        http-client-tls >=0.3.6.4 && <0.4,
        async >=2.2.5 && <2.3,
        network-uri >=2.6.4.2 && <2.8,
        wxr2pandoc

    hs-source-dirs:   app
    default-language: GHC2021

test-suite wxr2pandoc-test
    import:           warnings
    default-language: GHC2021
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base >=4.19.0.0 && <4.23,
        text ^>=2.1.3,
        tasty >=1.4 && <1.6,
        tasty-hunit >=0.10 && <0.11,
        pandoc >=3.7.0.2 && <3.9,
        pandoc-types ^>=1.23.1,
        wxr2pandoc
